name = "corta-2"
compatibility_date = "2024-11-27"
compatibility_flags = ["nodejs_compat"]

# Pages configuration
pages_build_output_dir = ".vercel/output/static"

# Environment variables for Workers
# You can set these with: wrangler secret put <NAME>
[vars]
# Public variables (non-sensitive)
# NEXT_PUBLIC_SUPABASE_URL = "your-supabase-url"

# Secret variables (sensitive) - set with wrangler secret put
# NEXT_PUBLIC_SUPABASE_ANON_KEY (use wrangler secret put NEXT_PUBLIC_SUPABASE_ANON_KEY)
# OPENAI_API_KEY (use wrangler secret put OPENAI_API_KEY)
# SUPERMEMORY_API_KEY (use wrangler secret put SUPERMEMORY_API_KEY) 